# Technical Terms Dictionary

| Term | Explanation | Source |
|---|---|---|
| **DDoS (Distributed Denial of Service)** | A malicious attempt to disrupt an online service by overwhelming it with massive amounts of internet traffic, typically from multiple compromised systems. | [cite: 4] |
| **IoT (Internet of Things)** | Refers to the network of physical devices, vehicles, home appliances, and other items embedded with electronics, software, sensors, actuators, and connectivity which enables these objects to connect and exchange data. | [cite: 7] |
| **Botnet** | A network of private computers infected with malicious software and controlled as a group without the owners' knowledge, e.g., to send spam or conduct DDoS attacks. Often involves compromised IoT devices. | [cite: 7, 19] |
| **TTPs (Tactics, Techniques, and Procedures)** | Describes the behavior of a threat actor. Tactics are high-level descriptions of behavior, techniques provide more detailed descriptions of behavior in the context of a tactic, and procedures are lower-level, highly detailed descriptions in the context of a technique. | [cite: 2, 9, 16] |
| **IoCs (Indicators of Compromise)** | Pieces of forensic data, such as data found in system log entries or files, that identify potentially malicious activity on a system or network. | [cite: 2, 9, 28] |
| **MITRE ATT&CK®** | A globally-accessible knowledge base of adversary tactics and techniques based on real-world observations. It's used as a foundation for threat modeling and methodology in the private sector, government, and cybersecurity product/service community. | [cite: 16, 63] |
| **Volumetric DDoS Attack** | A type of DDoS attack that attempts to consume the bandwidth either within the target network/service, or between the target network/service and the rest of the Internet. This is achieved by flooding the target with large amounts of traffic. | [cite: 16, 17] |
| **IP Spoofing** | The creation of Internet Protocol (IP) packets with a modified source address to hide the identity of the sender, impersonate another computing system, or both. It's a technique often used in DDoS attacks to make attribution difficult. | [cite: 25] |
| **Credential Stuffing** | An attack where stolen account credentials (usernames and passwords) are used to gain unauthorized access to user accounts through large-scale automated login requests directed against a web application. | [cite: 26, 35] |
| **Application Layer Attacks** | A form of DDoS attack that targets vulnerabilities in an application or server, with the goal of establishing a connection and exhausting server resources like CPU or memory. | [cite: 26] |
| **NVRs (Network Video Recorders)** | Devices typically used in IP video surveillance systems. They are essentially computers that record video in a digital format to a disk drive, USB flash drive, SD memory card or other mass storage device. Often targeted for inclusion in IoT botnets. | [cite: 19, 31] |
| **VPNs (Virtual Private Networks)** | Extend a private network across a public network, enabling users to send and receive data across shared or public networks as if their computing devices were directly connected to the private network. Can be used by attackers to obscure their origin. | [cite: 19, 32] |
| **Proxies** | Servers that act as intermediaries for requests from clients seeking resources from other servers. Can be used to mask the origin of traffic. | [cite: 19, 32] |
| **Tor Network** | Free and open-source software for enabling anonymous communication. It directs Internet traffic through a free, worldwide, volunteer overlay network to conceal a user's location and usage from anyone conducting network surveillance or traffic analysis. | [cite: 19, 32] |
| **Machine Learning (ML)** | A type of artificial intelligence (AI) that allows software applications to become more accurate at predicting outcomes without being explicitly programmed to do so. Used in cybersecurity for anomaly detection, identifying patterns indicative of attacks like DDoS. | [cite: 10, 20, 21, 22] |
| **Random Forest** | An ML algorithm used for classification and regression. It operates by constructing multiple decision trees during training and outputting the class that is the mode of the classes (classification) or mean prediction (regression) of the individual trees. Used here to identify features indicative of DDoS traffic. | [cite: 21] |
| **XGBoost** | An optimized distributed gradient boosting library designed to be highly efficient, flexible, and portable. It implements machine learning algorithms under the Gradient Boosting framework. Used alongside Random Forest for DDoS detection. | [cite: 21] |
| **Feature Importance Analysis** | A process in machine learning used to identify which input features (variables) are most relevant to the prediction outcome. In this context, it helped flag traffic patterns predictive of DDoS activity. | [cite: 22] |
| **WAF (Web Application Firewall)** | A type of firewall that monitors, filters, or blocks HTTP traffic to and from a web application. It helps protect web applications from attacks such as cross-site forgery, cross-site scripting (XSS), file inclusion, and SQL injection, among others. | [cite: 43] |
| **ROC (Receiver Operating Characteristic) Curve** | A graphical plot that illustrates the diagnostic ability of a binary classifier system as its discrimination threshold is varied. Used here to compare the performance of different ML models in detecting DDoS attacks. | [cite: 42] |
| **AUC (Area Under the Curve)** | Represents the degree or measure of separability provided by the ROC curve. It tells how much the model is capable of distinguishing between classes. Higher AUC indicates better model performance. | [cite: 42] |
